### ISSUE TITLE
-H does not include "jdbc" connector factory

### ISSUE THREAD

**Issue by andrus** [bootique/bootique-linkmove#24]
When I run the app that includes LInkMove with `-H`, I get the following output:

```
linkmove:
      #
      # Resolved as 'io.bootique.linkmove.LinkMoveFactory'.
      #

      connectorFactories:
            #
            # Resolved as 'List<io.bootique.linkmove.connector.IConnectorF
            # actoryFactory<? extends
            # com.nhl.link.move.connect.Connector>>'.
            #
            -
                  #
                  # Resolved as 'io.bootique.linkmove.connector.IConnector
                  # FactoryFactory<? extends
                  # com.nhl.link.move.connect.Connector>'.
                  #

                  #
                  # Type option: uri
                  # Resolved as 'io.bootique.linkmove.connector.URIConnect
                  # orFactoryFactory'.
                  #

                  type: 'uri'
                  connectors:
                        #
                        # Resolved as 'Map<String, String>'.
                        #
                        <string>: <string>
      extractorsDir: <string>
```

Somehow there's only a "uri" factory. Another factory ("jdbc") is not listed. This may be an issue with Bootique help generation engine, or with LM doc annotations.
