### ISSUE TITLE
RestConnector - connector based on Bootique JAX RS client

### ISSUE THREAD

**Issue by andrus** [bootique/bootique-linkmove#39]
LinkMove built-in URIConnector is very limited. Would be nice to use all Bootique JAX-RS client machinery (mapped targets, centralized REST client authentication, etc.) for LinkMove purposes. 

So let's create a separate module `bootique-linkmove-rest` (is there a need for `bootique-linkmove-rest-cayenne41` ?) that will allow all that stuff (and will not mess up dependencies for those apps not using REST connectors). The type of the connector (as referenced in the Extractor XMLs) will be`bq.rest`.

**Comment by andrus** [comment]
Here is how the REST connector can be configured:

extractor.xml:
```xml
<config>
    <type>json</type>
   <!-- This is the name of "jerseyclient" target -->
    <connectorId>toextract</connectorId>
    ...
</config>
```

app.yml:
```yaml
linkmove:
  extractorsDir: "classpath:..."
  connectorFactories:
    - type: "bq.rest" # Note: can't be combined with "uri" connector.. It replaces "uri" connector

# targets correspond to LM connector IDs, and can have authentication associated with them
# as well as other mapped target parameters
jerseyclient:
  targets:
    toextract:
      url: "http://127.0.0.1:8080/r1"
```
