### ISSUE TITLE
Parameterized URLs in RestConnector

### ISSUE THREAD

**Issue by andrus** [bootique/bootique-linkmove#40]
LM bundled `URIConnector` and the first version of `RestConnector` (#39) only allow working with static URLs. JAX-RS `WebTarget` on the other hand supports URL parameters, that can be substituted via various `resolveTemplate` methods. So let's take advantage of that and implement binding of extractor execution parameters to connector URL template.

Here is the API we are going to provide:

```yaml
jerseyclient:
  targets:
    toextract:
      url: "http://127.0.0.1:8080/r1/{p1}?name={p2}"
```

```java
LmTask task = ..
 Map<String, Object> params = RestConnector.bindTemplateValues()
                    .value("p1", 897L)
                    .value("p2", "a_Name")
                    .toExtractorParameters();
task.run(params);
```
